{
  "name": "@stdlib/utils/try-catch-async",
  "version": "0.0.0",
  "description": "If a function does not return an error, invoke a callback with the function result; otherwise, invoke a callback with a value `y`.",
  "author": {
    "name": "The Stdlib Authors",
    "url": "https://github.com/stdlib-js/stdlib/graphs/contributors"
  },
  "contributors": [
    {
      "name": "The Stdlib Authors",
      "url": "https://github.com/stdlib-js/stdlib/graphs/contributors"
    }
  ],
  "scripts": {},
  "main": "./lib",
  "repository": {
    "type": "git",
    "url": "git://github.com/stdlib-js/stdlib.git"
  },
  "homepage": "https://github.com/stdlib-js/stdlib",
  "keywords": [
    "stdlib",
    "stdutils",
    "stdutil",
    "utilities",
    "utility",
    "utils",
    "util",
    "asynchronous",
    "async",
    "try",
    "catch",
    "try-catch",
    "trap",
    "control",
    "flow",
    "condition",
    "conditional",
    "either-or"
  ],
  "bugs": {
    "url": "https://github.com/stdlib-js/stdlib/issues"
  },
  "dependencies": {},
  "devDependencies": {},
  "engines": {
    "node": ">=0.10.0",
    "npm": ">2.7.0"
  },
  "license": "Apache-2.0"
}
